name: Test and deploy Terraform app

on:
  push:
    branches:
      - main
      - cloudrun-module

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GITHUB_RUN_NUMBER: ${{ github.run_number }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.REGION }}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.4
          terraform_wrapper: false
      
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'

      - name: Build Terratest
        run: |
          cd test
          go mod init github.com/OmarMerghany/terraform-terratest-guide
          go mod tidy

      - name: Validate Terraform infrastructure
        run: cd examples && terraform init  && terraform validate

      - name: Run Terratest
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/key.json"
          export GCP_PROJECT_ID=$GCP_PROJECT_ID
          export REGION=$REGION
          export service_name="test-tf-$GITHUB_RUN_NUMBER"
          export image="gcr.io/google-samples/hello-app:1.0"
          cd test && go test -v -timeout 30m

