name: Test and deploy Terraform app

on:
  push:
    branches:
      - main

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GITHUB_RUN_NUMBER: ${{ github.run_number }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.3"
      
      - name: Set up GCP credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > key.json

      - name: Run tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=key.json
          export GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          cat $GCP_PROJECT_ID
          cp test/terraform_test.py terraform_test.py 
          python terraform_test.py
